# Generated by Django 4.2.6 on 2023-10-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mex_crm_models', models.IntegerField(default=5)),
                ('max_clients', models.IntegerField()),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
