# Generated by Django 4.2.6 on 2023-10-31 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='plans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='team.plans'),
        ),
    ]
