# Generated by Django 4.2.6 on 2023-10-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='max_clients',
            field=models.IntegerField(default=5),
        ),
    ]
