# Generated by Django 4.2.6 on 2023-11-05 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_plans_max_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plans',
            old_name='mex_crm_models',
            new_name='max_crm_models',
        ),
    ]
